<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="/assets/img/projecta-title.png" type="image/png" />
    <title>Ponto - Projecta</title>
    <link rel="stylesheet" href="/vendor/gainTime-2.2.2/css/gaintime.min.css" media ="screen" title="no title">
    <link rel="stylesheet" href="/assets/css/stylesheet.css" media ="screen" title="no title">
    <script type="text/javascript" src="/vendor/gainTime-2.2.2/js/gaintime.min.js"></script>
    <script type="text/javascript" src="/assets/js/jquery-3.3.1.min.js"></script>
    <script type="text/javascript" src="/assets/js/jquery.mask.min.js"></script>

    <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/solid.js" integrity="sha384-+Ga2s7YBbhOD6nie0DzrZpJes+b2K1xkpKxTFFcx59QmVPaSA8c7pycsNaFwUK6l" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/fontawesome.js" integrity="sha384-7ox8Q2yzO/uWircfojVuCQOZl+ZZBg2D2J5nkpLqzH1HY0C1dHlTKIbpRz/LG23c" crossorigin="anonymous"></script>
</head>
