-- MySQL Script generated by MySQL Workbench
-- Sáb 17 Fev 2018 21:53:41 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`members` (
  `id_members` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id_members`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id_users` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `level` ENUM('1', '2') NOT NULL,
  PRIMARY KEY (`id_users`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`schedule` (
  `id_schedule` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '	',
  `begin_time` INT NULL,
  `end_time` INT NOT NULL,
  `day` VARCHAR(45) NULL,
  `fk_members` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_schedule`),
  INDEX `fk_schedule_members_idx` (`fk_members` ASC),
  CONSTRAINT `fk_schedule_members`
    FOREIGN KEY (`fk_members`)
    REFERENCES `mydb`.`members` (`id_members`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`point`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`point` (
  `id_point` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `point` INT NOT NULL,
  `period` ENUM('in', 'out') NOT NULL,
  `time` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `members_id_members` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_point`),
  INDEX `fk_point_members1_idx` (`members_id_members` ASC),
  CONSTRAINT `fk_point_members1`
    FOREIGN KEY (`members_id_members`)
    REFERENCES `mydb`.`members` (`id_members`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
